/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothGattDescriptor */

#ifndef _Included_BluetoothGattDescriptor
#define _Included_BluetoothGattDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothGattDescriptor
 * Method:    getBluetoothType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattDescriptor_getBluetoothType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    clone
 * Signature: ()LBluetoothAdapter;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattDescriptor_clone
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    readValue
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattDescriptor_readValue
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    writeValue
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothGattDescriptor_writeValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    getUuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothGattDescriptor_getUuid
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    getCharacteristic
 * Signature: ()LBluetoothGattCharacteristic;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattDescriptor_getCharacteristic
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    getValue
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattDescriptor_getValue
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattDescriptor
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothGattDescriptor_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
