/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothGattCharacteristic */

#ifndef _Included_BluetoothGattCharacteristic
#define _Included_BluetoothGattCharacteristic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getBluetoothType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattCharacteristic_getBluetoothType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    clone
 * Signature: ()LBluetoothGattCharacteristic;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattCharacteristic_clone
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    readValue
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattCharacteristic_readValue
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    writeValue
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothGattCharacteristic_writeValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    startNotify
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothGattCharacteristic_startNotify
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    stopNotify
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothGattCharacteristic_stopNotify
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getUuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothGattCharacteristic_getUuid
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getService
 * Signature: ()LBluetoothGattService;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattCharacteristic_getService
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getValue
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattCharacteristic_getValue
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getNotifying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothGattCharacteristic_getNotifying
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getFlags
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_BluetoothGattCharacteristic_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    getDescriptors
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattCharacteristic_getDescriptors
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    init
 * Signature: (LBluetoothGattCharacteristic;)V
 */
JNIEXPORT void JNICALL Java_BluetoothGattCharacteristic_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BluetoothGattCharacteristic
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothGattCharacteristic_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
