/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothObject */

#ifndef _Included_BluetoothObject
#define _Included_BluetoothObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothObject
 * Method:    getBluetoothType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothObject_getBluetoothType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothObject
 * Method:    clone
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothObject_clone
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothObject
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothObject_delete
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothObject
 * Method:    operatorEqual
 * Signature: (LBluetoothObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothObject_operatorEqual
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
