/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothManager */

#ifndef _Included_BluetoothManager
#define _Included_BluetoothManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothManager
 * Method:    getBluetoothType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothManager_getBluetoothType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    getObject
 * Signature: (LBluetoothType;Ljava/lang/String;Ljava/lang/String;LBluetoothObject;)LBluetoothObject;
 */
JNIEXPORT jobject JNICALL Java_BluetoothManager_getObject
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject);

/*
 * Class:     BluetoothManager
 * Method:    getObjects
 * Signature: (LBluetoothType;Ljava/lang/String;Ljava/lang/String;LBluetoothObject;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothManager_getObjects
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject);

/*
 * Class:     BluetoothManager
 * Method:    getAdapters
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothManager_getAdapters
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    getDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothManager_getDevices
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    getServices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothManager_getServices
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    setDefaultAdapter
 * Signature: (LBluetoothAdapter;)Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothManager_setDefaultAdapter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BluetoothManager
 * Method:    startDiscovery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothManager_startDiscovery
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    stopDiscovery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothManager_stopDiscovery
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothManager_init
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothManager
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothManager_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
