/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothType */

#ifndef _Included_BluetoothType
#define _Included_BluetoothType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
