/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothAdapter */

#ifndef _Included_BluetoothAdapter
#define _Included_BluetoothAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothAdapter
 * Method:    getBluetoothType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothAdapter_getBluetoothType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    clone
 * Signature: ()LBluetoothAdapter;
 */
JNIEXPORT jobject JNICALL Java_BluetoothAdapter_clone
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    startDiscovery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothAdapter_startDiscovery
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    stopDiscovery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothAdapter_stopDiscovery
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothAdapter_getDevices
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothAdapter_getAddress
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothAdapter_getName
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getAlias
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothAdapter_getAlias
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    setAlias
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_setAlias
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BluetoothAdapter
 * Method:    getBluetoothClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_BluetoothAdapter_getBluetoothClass
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getPowered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothAdapter_getPowered
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    setPowered
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_setPowered
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BluetoothAdapter
 * Method:    getDiscoverable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothAdapter_getDiscoverable
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    setDiscoverable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_setDiscoverable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BluetoothAdapter
 * Method:    getDiscoverableTimeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_BluetoothAdapter_getDiscoverableTimeout
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    setDiscoverableTimout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_setDiscoverableTimout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     BluetoothAdapter
 * Method:    getPairable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothAdapter_getPairable
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    setPairable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_setPairable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BluetoothAdapter
 * Method:    getPairableTimeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_BluetoothAdapter_getPairableTimeout
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    setPairableTimeout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_setPairableTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     BluetoothAdapter
 * Method:    getDiscovering
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothAdapter_getDiscovering
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getUuids
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_BluetoothAdapter_getUuids
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    getModalias
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothAdapter_getModalias
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothAdapter
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothAdapter_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
