/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothEvent */

#ifndef _Included_BluetoothEvent
#define _Included_BluetoothEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothEvent
 * Method:    getType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothEvent_getType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothEvent
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothEvent_getName
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothEvent
 * Method:    getIdentifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothEvent_getIdentifier
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothEvent
 * Method:    executeCallback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothEvent_executeCallback
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothEvent
 * Method:    hasCallback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothEvent_hasCallback
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothEvent
 * Method:    init
 * Signature: (LBluetoothType;Ljava/lang/String;Ljava/lang/String;LBluetoothObject;LBluetoothCallback;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_BluetoothEvent_init
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     BluetoothEvent
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothEvent_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
