/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BluetoothGattService */

#ifndef _Included_BluetoothGattService
#define _Included_BluetoothGattService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BluetoothGattService
 * Method:    getBluetoothType
 * Signature: ()LBluetoothType;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattService_getBluetoothType
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattService
 * Method:    clone
 * Signature: ()LBluetoothAdapter;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattService_clone
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattService
 * Method:    getUuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BluetoothGattService_getUuid
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattService
 * Method:    getDevice
 * Signature: ()LBluetoothDevice;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattService_getDevice
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattService
 * Method:    getPrimary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BluetoothGattService_getPrimary
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattService
 * Method:    getCharacteristics
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_BluetoothGattService_getCharacteristics
  (JNIEnv *, jobject);

/*
 * Class:     BluetoothGattService
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BluetoothGattService_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
