/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ObjectArrayArgCallback */

#ifndef _Included_ObjectArrayArgCallback
#define _Included_ObjectArrayArgCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
